== Metadata
[cols="1h,1"]
|===
| CIP
| 4

| Title
| Field constants in generated cursor classes

| Author
//link to GitHub user page
| link:https://github.com/packpaul[packpaul]


| Created
| 2019-06-30


| Status
| discussion

| Discussion
//link to Google Group discussion thread
| https://groups.google.com/forum/#!topic/celesta-dev/2ScUhSqng8w


| JIRA
|

|===

== Motivation

When working with generated Celesta cursors developer have to indicate cursor fields as string literals, eg. `FooCursor.setRange("bar_open", true)`, which is fragile when the corresponding field of the grain is renamed. So it'd be nice having all grain fields be defined as constants in the generated cursors.

== Proposed Changes

1. Make `Column` class parameterized by the type of its value (`Column<T>`), and rewrite each of its descendants the following way: `IntegerColumn extends Column<Integer>`, `StringColumn extends Column<String>` etc.

2. Define all the columns of the table in the respective `final static` constants of the Cursor. Fill them in static initializer. 

3. Make `setRange` and `setFilter` methods parameterized and use the type capture, e. g.:

`<T> void setRange(Column<? super T> column, T from, T to)`

This will give us full type checking for `setRange` and `setFilter`.

== Compatibility, Deprecation, and Migration Plan

None. Leave old versions of `setRange` and `setFilter` in the `BasicCursor` along with new ones.

== Rejected Alternatives

Having all the table fields' names defined as constants in the generated cursors -- better than nothing, but still does not provide us with strict static checking.
