---
dist: xenial
addons:
  apt:
    packages:
      - graphviz
      - aspell-en

sudo: required

language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

script:
  - mvn generate-resources
  - errlist=$(for f in $(find . -name '*.adoc'); do    cat $f | aspell --master=en    --personal=./dict --run-together --run-together-limit=4 --run-together-min=2 list; done)
  - echo $errlist
  - "[ -z $errlist ]"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: target/generated-docs
  on:
    branch: master
