== Metadata
[cols="1h,1"]
|===
| CIP
| 2

| Title
| Dynamic Data Change for Cursor

| Author
//link to GitHub user page
| link:https://github.com/packpaul[packpaul]


| Created
| 2019-06-22


| Status
| discussion

| Discussion
//link to Google Group discussion thread
| https://groups.google.com/forum/#!topic/celesta-dev/I7jtbrEKv60


| JIRA
| https://jira.curs.ru/browse/PK-227

|===

== Motivation

In course of link:https://github.com/CourseIT/cymbals[Cymbals] project implementation which is using *Celesta* as one if its integral parts, it was noted that Celesta was lacking API for setting dynamically formed testing data to its cursors, for such data were obtained during run-time rather than in a static way. To overcome this problem a workaround solution based on a reflection mechanism of Java had to be provided that neither can cover all desired cases, nor is durable. It is believed that handling of similar use case could have a demand from other projects.

== Proposed Changes

To extend *API* by adding

[source,java]
----
BasicCursor.setFieldValue(String fieldName, Object value)
----

which would perform a type check and set the value.

[source,java]
----
Cursor Table.getCursor(CallContext ctx)
ViewCursor View.getCursor(CallContext ctx)
Sequence SequenceElement.getSequence(Context ctx)
ParameterizedViewCursor ParameterizedView.getCursor(Context ctx)
MaterializedViewCursor MaterializedView.getCursor(Context ctx)
----

methods for getting appropriate cursors of grain elements.

It should be noted that currently class `Table` can both represent tables with and without write access who are distinguished by `Table.isReadOnly()` property that returns `true` for read-only tables and `false` otherwise. Read-only tables in turn are using `ReadOnlyTableCursor` as a base class for their cursors. It is proposed to extend the table class hierarchy by including a separate `ReadOnlyTable` class, and have both `Table` and `ReadOnlyTable` be inherited from `BasicTable`:

.Tables class hierarchy    
[plantuml, cursors, png]
----
@startuml
DataGrainElement <|-- BasicTable
BasicTable <|-- Table
BasicTable <|-- ReadOnlyTable
@enduml
----

`Table.isReadOnly()` property should be marked as deprecated and return always `false`.

== Compatibility, Deprecation, and Migration Plan

Since API is extended backwards compatibility is preserved.

Methods for working with meta-information in Celesta already exist:

[source,java]
----
Grain Score.getGrain(String name)
T Grain.getElement(String name, Class<T> classOfElement)
----

they should be used in implementation.

== Rejected Alternatives

None
