== Metadata
[cols="1h,1"]
|===
| CIP
| 1

| Title
| Celesta Improvement Proposal Format

| Author
//link to GitHub user page
| link:https://github.com/inponomarev[inponomarev]


| Created
| 2019-05-22


| Status
| discussion

| Discussion
//link to Google Group discussion thread
| N/A


| JIRA
| N/A

|===

== Motivation
 
Since Celesta Project is acquiring larger user base, it becomes impossible for any single person to control all the aspects of its possible usage. 
Any compatibility-breaking changes in Celesta, although desirable for some users, can be harmful for others.

Thus a wide discussion of every change is needed in such a way that different Celesta users' needs can be considered and met.

Furthermore, this discussion should facilitate the spread of information about new features of Celesta.
Not only the immediate authors of the change proposal should benefit from the implementation of their ideas, but as large number of other users as possible.

In order not to miss any interested parties, we should set the formal rules of such discussion: where and how it should be carried out.

Last but not the least: we need a resilient process for Celesta development, not dependent on availability of any single person.

== Proposed Changes

1. Each change that modifies public API or breaks backwards compatibility should pass the CIP process.

2. The change should be formally written in the form of 'CIP' document. This document must be written in .adoc format, and committed to https://github.com/courseorchestra/cip project. If an author of the CIP does not have rights to push to CIP project directly, they can submit their CIP in pull request and request the rights from project owners: in order to simplify the process, rights to CIP project are given away freely.

3. CIP document should be 

[plantuml, diagram-state, png]     
....
[*] --> discussion : CIP initiated

discussion --> voting : start voting
discussion --> cancelling : start voting
voting --> implementation : at least 3 votes for, no votes against
voting --> discussion : at least 1 vote against
cancelling --> discussion : at least 1 vote against
cancelling --> cancelled : at least 3 votes for, no votes against
implementation --> implemented : feature is implemented 
....


== Compatibility, Deprecation, and Migration Plan

N/A


== Rejected Alternatives

None